import type { Metadata } from "next";
import { Rubik_Wet_Paint } from "next/font/google";

const rubic = Rubik_Wet_Paint({ subsets: ["latin"], weight: ["400"] });
import "./globals.css";
import Provider from "@/lib/providers/reactQueryProvider";
import { ChangeDarkMode } from "@/components/switch-dark";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const darkMode = cookie.get("dark-mode");

  return (
    <html lang="en">
      <body
        className={`${rubic.className} antialiased ${
          darkMode?.value === "true" ? "dark" : ""
        }`}
      >
        <div className=" min-h-screen flex flex-col gap-14 md:gap-28 justify-center items-center dark:bg-gradient-to-r dark:from-gray-800 dark:via-gray-900 dark:to-black bg-gradient-to-r from-blue-100 via-blue-200 to-blue-300">
          <div className="pt-10 md:pt-0 flex flex-col items-center font-bold">
            <h1 className="text-4xl font-bold text-red-800">
              Crypto Converter
            </h1>
            <h1 className="text text-black/55 dark:text-white/55">
              (Powered By CoinMarketCap API)
            </h1>
          </div>
          <Provider>{children}</Provider>
          <ChangeDarkMode></ChangeDarkMode>
        </div>
      </body>
    </html>
  );
}
